### ISSUE TITLE
Stop the pulsating colon between HH and mm

### ISSUE THREAD

**Issue by cretancapital** [Kolcha/DigitalClock5#14]
Hi there,
Can you please enable feature to stop the blinking of the : colon that separates HH:mm? I find it very distracting.

Thanks!
CC.

**Comment by Kolcha** [comment]
option is already here, look for "flashing separator", very likely on "Format" tab (have no computer these days, so can't say anything precisely)
--
Sent from  Mail app for Android Monday, 04 November 2024, 08:49PM +01:00 from cretancapital  ***@***.*** :

**Comment by cretancapital** [comment]
Thanks for such a fast response! Found it under "Appearance" Tab. thank you !
