### ISSUE TITLE
"Electronic Empty" skin missing from Digital Clock 5

### ISSUE THREAD

**Issue by EmanueleGiannuzzi** [Kolcha/DigitalClock5#15]
The "Electronic Empty" skin is missing from the list. 
I tried to move it from the "Digital Clock 4" folder, but I can't find it. 
I suppose it's handled internally, so I'm asking for a port.

**Comment by Kolcha** [comment]
yes, "electronic empty" skin is built-in, you can find it's source in Digital Clock 4 sources:
https://github.com/Kolcha/DigitalClock4/tree/master/digital_clock/resources/electronic_empty
just copy this folder to skins folder. old skins are fully supported and will work as is.
"official" place for custom skins can be found in the documentation here:
https://github.com/Kolcha/DigitalClock5/wiki/Where-to-put-custom-skins
but it is totally fine to the skin into "skins" folder with default skins.
--
Sent from  Mail app for Android Thursday, 28 November 2024, 11:49AM +01:00 from Jan  ***@***.*** :

**Comment by EmanueleGiannuzzi** [comment]
Thank you
